### ISSUE TITLE
[BUG] Move ultrasoon sensors down a layer

### ISSUE THREAD

**Issue by Someone-s-out-there** [Someone-s-out-there/ProjectCarHAN#41]
**Describe the bug**
the ultra soon sensors are mounted slightly to high and should be moved down a layer on the car to ensure that even low objects are detected

**Comment by Someone-s-out-there** [comment]
this is dependent on issue #47

**Comment by GhostJulian** [comment]
# UPDATE 23-11-2023

Ultrasoon modules tijdelijk van Robot-auto verwijderd zodat het makkelijker is om verkeerd aangesloten draden op de Schmitt trigger  te vinden en op te lossen.
