### ISSUE TITLE
Bouwplan maken

### ISSUE THREAD

**Issue by Someone-s-out-there** [Someone-s-out-there/ProjectCarHAN#77]
Make. Van een bouwplan 

Voor 7 december, dit is de laatste projecturen die ingeroosterd zijn voor de inleverdatum

1 globale lijn, en dan in zoomen op een onderwerp per keer

Presentatie visueel te volgen van achter in.

**Comment by GhostJulian** [comment]
[Bouwplan Presentatie.pdf](https://github.com/Someone-s-out-there/ProjectCarHAN/files/13632495/Bouwplan.Presentatie.pdf)
Op zondag 10-12-2023 is dit ingeleverd.
